"""Initial schema: user, project, saved_schedule

Revision ID: 93de91829abc
Revises: 
Create Date: 2026-08-13 22:24:19.746705

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# input_modules/optimized_data are stored as opaque JSON blobs (see
# database.py) - jsonb is the better default on Postgres (more compact,
# faster to (de)serialize) with no downside for this access pattern, while
# SQLite keeps using plain JSON since it doesn't have a jsonb type. This
# only affects databases that run this migration fresh (i.e. new Postgres
# instances); it doesn't retroactively alter columns on databases that
# already applied this revision against SQLite.
JSON_VARIANT = sa.JSON().with_variant(postgresql.JSONB(), "postgresql")


# revision identifiers, used by Alembic.
revision = '93de91829abc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('input_modules', JSON_VARIANT, nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('saved_schedule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('optimized_data', JSON_VARIANT, nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('saved_schedule')
    op.drop_table('project')
    op.drop_table('user')
    # ### end Alembic commands ###
