"""add indexes on project.user_id and saved_schedule.project_id

Revision ID: dc3c2858ea28
Revises: 93de91829abc
Create Date: 2026-08-17 16:37:41.435470

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc3c2858ea28'
down_revision = '93de91829abc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('saved_schedule', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_saved_schedule_project_id'), ['project_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('saved_schedule', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_saved_schedule_project_id'))

    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_user_id'))

    # ### end Alembic commands ###
